name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: docker build . --file "Backend/Kassasysteem backend/Walking Skeleton/Walking Skeleton LOUPE/Dockerfile" --tag my-image-name:$(date +%s)
