name: UserHandler.Microservice CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PATH_TO_DOCKERFILE: './Backend/Kassasysteem/User.Microservice/Dockerfile'
  DOCKER_IMAGE_NAME: user.microservice:latest
  DOCKER_REPO_NAME: 441576/user.microservice

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    docker:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Build docker image
          run: docker build . --file $PATH_TO_DOCKERFILE --tag $DOCKER_IMAGE_NAME
        - name: docker login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCTOKEN }}
        - name: tag image
          run: docker tag $DOCKER_IMAGE_NAME $DOCKER_REPO_NAME
        - name: push image
          run: docker push $DOCKER_REPO_NAME:latest
